avatar: true
cookies:
  msToken: 710-fIIacqPfoNUNM8EKjH2ev0veFV2YZCtCfs_HoN7kjpBKubLAODdh0nStKywolHK2nsJFHmdimUN23q-lo41pxjuiNMoqG1p_yUoIKU0CJ9bX-Q0638LXozcxspQnrzDnHB4M_3Hu3GljVuPYvv-8nHrxp4Xqkw-Bcr0MeothxDuPtHlEBA==
  odin_tt: a19f20351de5ed35a078f09115d098328b025656113ec0e35dfc4f7e1cf04dea5edd7d8176cf7070e0ff8f53414adeb8
  passport_csrf_token: c2a7091feddce96551be4436e03ca3f3
  sid_guard: 5e5adf6c506e880b1e0959afb5f6cb80%7C1739188609%7C5183984%7CFri%2C+11-Apr-2025+11%3A56%3A33+GMT
  ttwid: 1%7Cxo2A_Uas39HcSPeQYZRGlCLpHonxCq5l8gMlrUPsh3I%7C1733400452%7C9f770c01cd093794153133a14108c93b5b6e6e18971372c21ecffe37f1938da0
cover: true
database: true
end_time: '2025-04-07'
folderstyle: true
increase:
  allmix: false
  like: false
  mix: false
  music: false
  post: true
json: true
link:
- https://www.douyin.com/user/MS4wLjABAAAAIknhyIhDxQe6fsexjsu0qL7uzOUdWsINm2PCOLyzZgU
mode:
- post
music: true
number:
  allmix: 1
  like: 5
  mix: 5
  music: 5
  post: 0
path: ./downloaded/
start_time: '2025-04-01'
thread: 5
